# Generated by Django 4.0.5 on 2022-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.CharField(default=1659340482.0984337, max_length=50),
        ),
        migrations.AlterField(
            model_name='mixer',
            name='fan_speed',
            field=models.IntegerField(default=1000, verbose_name='Скорость вентилятора'),
        ),
        migrations.AlterField(
            model_name='mixer',
            name='mixer_type',
            field=models.CharField(max_length=50, verbose_name='Тип Миксера'),
        ),
    ]
