# Generated by Django 4.0.5 on 2022-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_img_url_alter_mixer_fan_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blender',
            name='fan_speed',
            field=models.IntegerField(default=500, verbose_name='Скорость вентилятора'),
        ),
        migrations.AlterField(
            model_name='blender',
            name='volume',
            field=models.IntegerField(default=1, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.CharField(default=1659346652.627092, max_length=50),
        ),
        migrations.AlterField(
            model_name='combine',
            name='max_power',
            field=models.IntegerField(default=50, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='combine',
            name='volume',
            field=models.IntegerField(default=2, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='height',
            field=models.IntegerField(default=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='length',
            field=models.IntegerField(default=60, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='width',
            field=models.IntegerField(default=50, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='mixer',
            name='bowl_size',
            field=models.IntegerField(default=5, verbose_name='Размер чаши'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='height',
            field=models.IntegerField(default=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='length',
            field=models.IntegerField(default=60, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='width',
            field=models.IntegerField(default=50, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='В запасе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='teapot',
            name='max_power',
            field=models.IntegerField(default=70, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='teapot',
            name='volume',
            field=models.IntegerField(default=2, verbose_name='Объем'),
        ),
    ]
