# Generated by Django 4.0.5 on 2022-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cart_customer_id_alter_category_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NULL', 'In Cart'), ('CR', 'Created'), ('PAID', 'Paid'), ('IS_DEL', 'Is Delivering'), ('DEL', 'Delivered')], default='NULL', max_length=6),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(default=1659536116.057198, max_length=50, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1659536116.0517442, upload_to='uploads/'),
        ),
    ]
