# Generated by Django 4.0.5 on 2022-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_status_alter_category_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(default=1659538127.4636939, max_length=50, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PAID', 'Paid'), ('IS_DEL', 'Is Delivering'), ('DEL', 'Delivered')], default='CR', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1659538127.4580467, upload_to='uploads/'),
        ),
    ]
