# Generated by Django 4.0.5 on 2022-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_total_quantity_order_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='main.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='1660306470', max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='1660306470', max_length=80, verbose_name='Город'),
        ),
    ]
