# Generated by Django 4.0.5 on 2022-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_product_name_remove_order_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='1660313722', max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='1660313722', max_length=80, verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
