# Generated by Django 4.0.5 on 2022-08-13 11:08

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_address_alter_order_city_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='1660388887', max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='1660388887', max_length=80, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('CR', 'Created'), ('PAID', 'Paid'), ('IS_DEL', 'Is Delivering'), ('DEL', 'Delivered')], default='CART', max_length=6),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_name', models.CharField(default=0, max_length=50, verbose_name='Название товара')),
                ('unit_price', models.IntegerField(default=0, verbose_name='Цена')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='main.product')),
            ],
        ),
    ]
