# Generated by Django 4.0.5 on 2022-08-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_category_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(default=1659598987.7102501, max_length=50, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1659598987.7067294, upload_to='uploads/'),
        ),
    ]
