# Generated by Django 4.0.5 on 2022-08-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_img_url_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(default=1659599926.2844577, max_length=50, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1659599926.2809691, upload_to='uploads/'),
        ),
    ]
