# Generated by Django 4.0.5 on 2022-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_category_img_url_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(default=1659944071.865046, max_length=50, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1659944071.8614764, upload_to='uploads/'),
        ),
    ]
