# Generated by Django 4.0.5 on 2022-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orderitem_order_id_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='1660548835', max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='1660548835', max_length=80, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.IntegerField(default=None, verbose_name='Цена'),
        ),
    ]
