# Generated by Django 4.0.5 on 2022-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Цена заказа')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('city', models.CharField(default='', max_length=80, verbose_name='Город')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('CART', 'Cart'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('IS_DELIVERING', 'Is Delivering'), ('DELIVERED', 'Delivered')], default='CART', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('product_name', models.CharField(default=0, max_length=50, verbose_name='Название товара')),
                ('unit_price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
