# Generated by Django 4.0.5 on 2022-08-23 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Order price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('city', models.CharField(default='', max_length=80, verbose_name='City')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Address')),
                ('status', models.CharField(choices=[('CART', 'Cart'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('IS_DELIVERING', 'Is Delivering'), ('DELIVERED', 'Delivered')], default='CART', max_length=13)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('product_name', models.CharField(max_length=50, null=True, verbose_name='Product name')),
                ('unit_price', models.IntegerField(null=True, verbose_name='Price')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
            options={
                'verbose_name': 'Item in order',
                'verbose_name_plural': 'Items in order',
            },
        ),
    ]
