# Generated by Django 4.0.5 on 2022-08-19 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=160, null=True, verbose_name='О себе')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('\\d{11}', 'Enter a valid phone number. Minimum 11 digits', code='invalid')], verbose_name='Номер телефона')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Область')),
            ],
        ),
    ]
