# Generated by Django 4.0.5 on 2022-08-04 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('-{1}\\d+', 'Enter a valid age', code='invalid')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('\\d{11}', 'Enter a valid phone number. Minimum 11 digits', code='invalid')]),
        ),
    ]
