# Generated by Django 4.0.5 on 2022-08-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.ImageField(max_length=50, upload_to='category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('in_stock', models.IntegerField(default=0, verbose_name='В запасе')),
                ('img', models.ImageField(upload_to='uploads/')),
                ('category', models.ManyToManyField(to='shop.category')),
                ('content_type', models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Blender',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('volume', models.IntegerField(default=1, verbose_name='Объем')),
                ('fan_speed', models.IntegerField(default=500, verbose_name='Скорость вентилятора')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Combine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('volume', models.IntegerField(default=2, verbose_name='Объем')),
                ('max_power', models.IntegerField(default=50, verbose_name='Мощность')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('height', models.IntegerField(default=100, verbose_name='Высота')),
                ('width', models.IntegerField(default=50, verbose_name='Ширина')),
                ('length', models.IntegerField(default=60, verbose_name='Длина')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('mixer_type', models.CharField(max_length=50, verbose_name='Тип Миксера')),
                ('fan_speed', models.IntegerField(default=1000, verbose_name='Скорость вентилятора')),
                ('bowl_size', models.IntegerField(default=5, verbose_name='Размер чаши')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('height', models.IntegerField(default=100, verbose_name='Высота')),
                ('width', models.IntegerField(default=50, verbose_name='Ширина')),
                ('length', models.IntegerField(default=60, verbose_name='Длина')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Teapot',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('volume', models.IntegerField(default=2, verbose_name='Объем')),
                ('max_power', models.IntegerField(default=70, verbose_name='Мощность')),
            ],
            bases=('shop.product',),
        ),
    ]
